FROM node:25.0.0-alpine AS builder

WORKDIR /app

COPY src/package*.json ./

RUN npm install --only=production

COPY src ./

FROM node:25.0.0-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app .

EXPOSE 5000

CMD [ "node", "server.js" ]
